ParmEd/ParmEd

chemistry/amber/_amberparm.py
This fixes issues in which someone may change some atomic masses and those
atomic numbers will be reset to strange values if ATOMIC_NUMBER is not set in
the topology file.  This change makes it so the atomic number will be set at the
beginning of the Python program and not change (unless requested to) for the
rest of the script.
=> Remember the atomic number after the first time it was set.

ParmedTools/ParmedActions.py, test/test_parmedtools_actions.py
Also add a -toppar flag so that 'chamber' will try to determine what the file
type of each file is based on extension (or the presence of 'top' or 'par' in
the case that the extension is '.inp'). This should make input simpler.
Add a test for the new globbing functionality.
=> Do filename globbing in the chamber action.

ParmedTools/ParmedActions.py
This can substantially decrease the runtime for processing a *lot* of parameters.
=> Allow parameter sets to *not* be condensed in the chamber action

ParmedTools/ParmedActions.py, chemistry/amber/_amberparm.py, chemistry/amber/_chamberparm.py
In case atoms need to be re-ordered by ParmEd.
This fixes a bug where coordinates were assigned incorrectly if the PSF file had
non-contiguous molecules following the CHAMBER action.
=> Load the coordinates into the generated PSF file before converting it to a prmtop

chemistry/charmm/psf.py, chemistry/structure.py, chemistry/topologyobjects.py, test/test_chemistry_charmm.py, test/test_chemistry_structure.py
This adds support for reading (and optionally writing) a SEGID written in columns 73 to 76 (inclusive) in the PDB file. The standard makes no specification for these columns, so we can assign those columns to be a "segid" while still supporting fully compliant PDB files.
Also provide a "`charmm` keyword for `Structure.write_pdb` and `structure.write_PDB` (that defaults to `False`) that will optionally print out the SEGID in columns 73 through 76 (left-justified).
Finally, this changes the `system` string that the `CharmmPsfFile` parsed into this segid so that PSF -> PDB will be more in line with what CHARMM users expect (assuming they use `charmm=True` when writing a PDB file).
Unrelated changes include truncating a bunch of strings in the PDB writing routine to make sure they do not …
=> CHARMM PDB file support

chemistry/amber/_amberparm.py
Apparently this can cause problems during a chamber call if the system was not solvated? Or something.
=> Protect against missing keys.

setup.py
This fixes builds when the Python version is <= 2.6 by simply omitting the
openmm package in that case (since it has Py24/Py25-incompatible syntax).
=> Simplify setup script

test/test_openmm_amber.py, test/test_openmm_charmm.py, test/test_openmm_reporters.py
I presume these failures are caused by blowing the memory limits placed on
tests. I think this is caused by rogue System objects and Context objects
sticking around in memory. First stab to get this working is to just call a
gc.collect to try and force the garbage collector to clean up those objects.
If need be, I can del them, but I'd rather not have to.
=> Attempt to prevent random Travis failures

src/CompatibilityMacros.h, src/_rdparm.cpp, test/test_chemistry_amber.py
This probably explains why Python3 has been so much slower in the tests than
Python 2... This commit also adds a test to make sure that the optimized reader
was built and is importable.
=> Fix the Python 3 optimized C++ reader.

setup.py
The extension is simply an optional prmtop reader that parses topology files ~3-5x faster than the pure Python version.
=> Build ParmEd without the compiled extension if Py dev headers are not present

chemistry/topologyobjects.py
Also deletes an unused (legacy) method from DihedralType.
=> Make __repr__ printouts consistent with attribute names

chemistry/structure.py
Have createSystem recognize when a Structure has changed and then prune empty terms when applicable. Add notes in the docstring detailing this.
=> Improve behavior of `createSystem` when the structure is modified

chemistry/structure.py
This prints more information about the system, including the number of atoms,
residues, bonds, whether PBC are present, and whether the Structure is
parametrized or not.
For example:
```Python
>>> import chemistry as chem
>>> l = chem.load_file('test/files/trx.prmtop')
>>> k = chem.load_file('test/files/solv.prmtop')
>>> j = chem.load_file('test/files/4lzt.pdb')
>>> i = chem.load_file('test/files/4LZT.cif')
>>> l
<AmberParm 1654 atoms; 108 residues; 1670 bonds; parametrized>
>>> k
<AmberParm 29881 atoms; 9257 residues; 29893 bonds; PBC; parametrized>
>>> j
<Structure 1164 atoms; 274 residues; 0 bonds; PBC; NOT parametrized>
>>> i
<Structure 1164 atoms; 274 residues; 0 bonds; PBC; NOT parametrized>
```
=> Add informative __repr__ to Structure

chemistry/charmm/psf.py, test/test_chemistry_charmm.py
Apparently residue numbers in CHARMM psf files can be adorned with trailing
insertion codes.  Support these PSF files in the parser. Slows down PSF parsing
a little, but not too much. If reading becomes much too slow, I'll write a
C++-optimized version.
=> Expand CHARMM PSF parsing generality.

chemistry/charmm/_charmmfile.py, chemistry/charmm/parameters.py, chemistry/modeller/residue.py, test/test_chemistry_charmm.py
Still doesn't convert the IC table into a set of cartesian coordinates. But you
can now access the patches and residue templates from the ``residues`` and
``patches`` attributes of the resulting ``CharmmParameterSet``
=> Have CharmmParameterSet parse RESI cards from stream and RTF files

chemistry/geometry.py, chemistry/structure.py, chemistry/topologyobjects.py, test/test_chemistry_structure_slicing.py
It is not the most efficient way of doing things, but it's reasonably simple and
fairly expressive. There are a number of hopefully intuitive ways of indexing a
subset of atoms from a given Structure:
By atom
-------
`struct[10]` Returns the 11th Atom instance in the structure
By atom slice
-------------
`struct[:10]` Returns new Structure with 1st 10 atoms and all their parameters
By Amber mask
-------------
`struct[':1-5@CA']` Returns a new Structure with CA atoms of the 1st 5 residues
By chain, residue, and atom indexing/listing/slicing (indexes start from 1 and
are sequential); selections return Structure (if selecting more than 1 atom)
------------------------------------------------------------------------------
`struct[['A', 'B'], 10￼5, :]` all atoms of residues 10-100 (every 5) of …
=> Implement fancy indexing for `Structure`

doc/index.rst
This should address #123 to some degree.
The webpage is already live on http://parmed.github.io/ParmEd/html/index.html
@kyleabeauchamp -- how's this?
=> Add a "future directions" and link to PDF slides in homepage.

chemistry/__init__.py, chemistry/charmm/parameters.py, chemistry/gromacs/__init__.py, chemistry/gromacs/_cpp.py, chemistry/gromacs/_gromacsfile.py, chemistry/gromacs/gromacstop.py, chemistry/parameters.py, chemistry/structure.py, chemistry/topologyobjects.py, test/files/1aki.charmm27.top, test/files/1aki.ff99sbildn.top, test/test_chemistry_structure.py
The Gromacs topology file parser is now working, and correctly parses out and populates a `Structure` instance with bonds, angles, dihedrals, exceptions, cmaps, impropers, and even R-B torsions.  Atom types are assigned, but no other parameter types are yet assigned.
Next stage is to implement a Gromacs topology file *writer*, then start to parse in parameter types.
This also adds one test, but more are planned.
=> Gromacs support

chemistry/amber/_amberparm.py, chemistry/amber/_chamberparm.py, chemistry/amber/_tinkerparm.py, chemistry/charmm/psf.py, chemistry/exceptions.py, chemistry/formats/registry.py, chemistry/gromacs/gromacsgro.py, chemistry/gromacs/gromacstop.py, chemistry/openmm/__init__.py, chemistry/openmm/reporters.py, chemistry/openmm/topsystem.py, chemistry/structure.py, chemistry/utils/decorators.py, devtools/travis-ci/install.sh, doc/openmm.rst, test/test_format_conversions.py, test/test_openmm_amber.py, test/test_openmm_charmm.py, test/test_openmm_gromacs.py
This PR adds support for loading a Structure from an OpenMM `Topology` instance, optionally filling in parameters from a populated `System` object.
Round-tripping (i.e., Amber files -> ParmEd -> OpenMM -> ParmEd -> OpenMM) gives identical forces and energies for the standard Amber potential terms (still need to check CHARMM and Gromacs tests).  Among other things, this allows you to convert an OpenMM Topology/System combo into an Amber prmtop file.
Still needed:
=> OpenMM Topology/System -> Structure conversion

parmed/utils/decorators.py
Gives a helpful error message if OMM is available, but is too old to work with ParmEd.
=> Properly recognize OMM versions that are too old.

parmed/gromacs/gromacsgro.py
Significantly improves performance of parsing GRO files (mainly relevant for
larger GRO files) by using generator comps instead of loops-with-conditionals.
Also fixed a bug wherein the y-component of the velocity was assigned to both
vy and vz.
=> Improvements to GRO parser

parmed/amber/parameters.py
Hi Jason,
In creating the .frcmod object, I ran into the following error message:
```
leeping@not0rious:~/projects/VSP27-Protein/XMLConvert$ ./oxml-aprm.py Checked/a99sc-v2-r1/a99sc-v2-r1.xml
Traceback (most recent call last):
File "./oxml-aprm.py", line 124, in <module>
parameters._DihedralTerm(pk=k, phase=f, periodicity=p, dihtype=dtyp))
File "/home/leeping/local/lib/python2.7/site-packages/parmed/amber/parameters.py", line 87, in __init__
improper=improper)
TypeError: __init__() got an unexpected keyword argument 'improper'
```
It turns out that `DihedralType` doesn't take an "improper" argument although `Dihedral` does.  I believe that deleting the keyword argument in `amber/parameters.py` doesn't have any ill effects.  Can you confirm this?
Thanks,
- Lee-Ping
=> Remove a keyword argument that was causing DihedralType() to crash

parmed/periodic_table.py
Profiling Amber topology file reading for dhfr_cmap_pbc.parm7 yielded the following report:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
56057    1.608    0.000    2.054    0.000 periodic_table.py:228(element_by_mass)
56057    1.206    0.000    1.380    0.000 topologyobjects.py:433(__init__)
6872938    0.447    0.000    0.447    0.000 {abs}
1    0.395    0.395    0.395    0.395 {parmed.amber._rdparm.rdparm}
1    0.375    0.375    0.804    0.804 _amberparm.py:1430(_load_bond_info)
1    0.290    0.290    2.659    2.659 _amberparm.py:471(load_atom_info)
1    0.248    0.248    2.090    2.090 _amberparm.py:1346(_load_atoms_and_residues)
```
Determining element by mass is the most expensive operation, since it loops through every element to pull out the best match. …
=> Improve performance of Amber topology file parsing

parmed/topologyobjects.py
This gives a slight improvement in indexing a `TrackedList`.  It seems that `TrackedList.__getitem__` is one of the routines that `supercell.parm7` spends the most time in, which indicates it's unnecessarily expensive.  I should probably stop overriding it and just settle with a slice returning a `list` instead of a `TrackedList`...  We'll see how much that breaks.
In the meantime, this gives a ~10% performance boost (reducing parsing time from 10 to 9 seconds on my desktop).  Not too much.
At this point, the bottleneck *seems* to be `Atom` instantiation. There's nothing that I can see to address that short of migrating to Cython.  (Of course, you could just use PyPy instead :)).
=> Attempt to make TrackedList.__getitem__ a little cheaper.

parmed/formats/pdb.py
They were previously identified as "alternate locations". But not all PDB files
obey the unique-atom-names-in-each-residue rule, so don't stash atoms as
alternate locations unless the altloc is *actually* defined.
=> Fix PDB file parsing when residues have 2 atoms with the same name

parmed/structure.py
If someone changed atom.xx, xy, or xz, the coordinates could become out-of-date
if any cached versions were around.  This simplifies the code, at the expense of
some computational efficiency, but it's better to be correct and slow than
potentially incorrect and fast.
And you can still be almost just as fast, you just have to store a reference to
the Structure.coordinates and work on that, rather than the coordinates
attribute directly.  So:
coords = struct.coordinates
... do stuff with coords
rather than
... do stuff with struct.coordinates
=> Make sure coordinates attribute is *always* up-to-date.

parmed/topologyobjects.py, test/test_parmed_amber.py
`TrackedList.__getitem__` was one of the costliest functions in supercell.parm7
parsing (as part of the `_load_dihedrals` function). Profilers indicate that a
*lot* of time is spent in `TrackedList.__getitem__`. By no longer overriding this
function, this *should* push `TrackedList.__getitem__` into C code (as that is
where the Python list is implemented).
=> Stop overriding TrackedList.__getitem__ and __getslice__

parmed/scripts.py, parmed/tools/checkvalidity.py, parmed/tools/parmed_cmd.py
- Exit following bad commands *only* if the commands are being read from a
script or file. If they are being typed in, do not quit following bad commands
- Correctly catch fatal warnings in addition to hard errors in the interactive
interpreter (when reading stdin from a TTY, that is).
Fixes #243
=> Fix some small issues with the interactive interpreter

parmed/tools/parmed_cmd.py
Doesn't hurt.  Works in addition to existing modes.  You can now get help in the
following 3 ways:
```
help <command>
?<command>
<command>?
```
=> Support IPython-like help syntax in parmed CLI

parmed/charmm/psf.py, parmed/formats/psf.py, parmed/gromacs/gromacstop.py, parmed/structure.py, test/test_parmed_structure.py
This allows you to write the desired format in a *single* place, with any
necessary conversions being done for you automatically. It also handles
Amber-style formats as well as possible, determining in most instances whether a
structure can be cast as a ChamberParm when AmberParm is not flexible enough.
File type is determined from filename extension *or* explicit direction.
This also fixes writing PSF files from Structure instances that were *not*
parsed from PSFs (since the `groups` list did not have a `nst2` attribute.
This fixes #106.
=> Add Structure.save function

parmed/tools/actions.py
- Avoids O(N^2) string concatenation algorithms for building the string return
values (which is a consequence of Python strings being immutable). Uses the
recommended `join()` method instead.
- Changes `printXYZ.__str__` to `__repr__` (and returns the same thing for the
` __str__` method) in order to make these methods play nicer in the interactive
Python interpreter.
=> Fix up print methods in parmed.tools

parmed/structure.py, test/test_parmed_structure.py, test/test_parmed_structure_slicing.py
This PR closes #267 (and #274)
The new behaviors here:
- Selecting a slice, a mask, or a mask array will *always* return a `Structure` (or subclass) instance, even if it only selects a single atom.
- Selecting a single atom, by either `struct[int]`, `struct[int, int]` or `struct[str, int, int]` (which amounts to picking a single atom, a single atom from a single residue, or a single atom from a single residue from a single chain) still returns just an `Atom`, but runs orders of magnitude faster now (returns almost instantly, as you would expect it should, except for chain selections since chains need not be contiguously listed in a PDB file)
- Selections involving slices and Amber masks that do not select *anything* return an empty `Structure` instance instead of `None`
- Truthiness was …
=> Improves behavior of slicing

parmed/amber/amberformat.py, parmed/amber/netcdffiles.py, parmed/charmm/psf.py, parmed/formats/mol2.py, parmed/formats/registry.py, parmed/gromacs/_cpp.py, parmed/utils/io.py, test/test_parmed_formats.py, test/test_parmed_genopen.py
A couple notes here:
- Remote NetCDF files do not work -- the NetCDF implementations require a fd
attribute, which urlopen-returned objects don't have (at least in Py2; Py3
hasn't been checked)
- The optimized Amber topology file reader only supports local files, so urls
force the use of the "slow" (i.e., pure python) reader. In this case, the
parser will likely not be rate-limiting (the network will be).
Tests were added first in TDD-style.
=> Implement remote file support in load_file

parmed/scripts.py, parmed/tools/exceptions.py, test/test_parmedtools_actions.py
=> Make SeriousParmWarning fatal by default in Python

parmed/gromacs/gromacstop.py, parmed/structure.py, test/files/12.DPPC/topol3.top, test/test_parmed_amber.py, test/test_parmed_gromacs.py
Attempt to fix #292 
@mpharrigan -- try this PR out and see if it does the trick.  The `[ molecules ]` section gets a lot longer, since I decided against reordering the atoms.  If I reordered atoms, then the following would *not* work:
```Python
parm.save('gmx.top', format='gromacs')
parm.save('gmx.gro')
```
Since the ordering on `gmx.top` would change relative to `parm`, and the generated GRO file wouldn't match.  You'd have to do something like this instead:
```Python
top = parm.gromacs.GromacsTopologyFile.from_structure(parm)
top.write('gmx.top')
top.save('gmx.gro')
```
And there would be really no good way of catching this mistake.  It's better if everything can have the same order (not always possible).  Let me know if this PR fixes the issues you're seeing and I'll merge it.
=> Try to fix the molecule ordering problem in Gromacs topologies

parmed/formats/registry.py, parmed/tools/parmlist.py, test/test_parmed_formats.py
This closes #290 (and other related threads; it's been brought up a couple times).
This is done in a way that should be future-proof against any parser that may support that argument in the future.  It looks at the argument names and discards `structure` from `**kwargs` IFF `structure` is not found in that argument list.
=> Always allow `structure` keyword in `load_file` and ignore it when it's not used

parmed/formats/pdb.py, test/test_parmed_formats.py
The following additions were made to the PDB and CIF parsers:
- Parse X-Ray resolution from both CIF and PDB files with test cases (Closes #297)
- Fixes CIF parser when molecule has multiple models (e.g., PDB ID 2KOC), and adds test
- Adds ability to write PDB and CIF files with multiple `MODEL`s, with corresponding tests
- Simplifies coordinate handling in the writing routines by eliminating the now-vestigial numpy-free support. Just use `ndarray` for all of the coordinates, which significantly simplifies the code.
=> Improvements to CIF and PDB parser/writer

parmed/formats/mol2.py, test/test_parmed_formats.py
=> Fix Mol2 file writing when `Structure` does not have defined types

parmed/formats/pdb.py, test/files/bigz.pdb, test/test_parmed_formats.py
This is a fairly rare bug and occurs when one of the Z-coordinates of a PDB file is the full 8 characters.  Reported by Rohith Mohan on the Amber mailing list.
=> Fix small bug in PDB parser

parmed/amber/_chamberparm.py
Hi Jason,
This addresses an issue encountered when using parmed's chamber command with certain parameter files, including 'par_all36_cgenff.prm' and 'par_opls_aam.inp'. If I understand correctly, the use of the CHARMM force field and its unique terms with a given parm file is triggered by the presence of the string 'CHARMM' under the flag 'FORCE_FIELD_TYPE'. For most CHARMM force field files (e.g. CHARMM36), this will be already be present in the first line of the header of the parameter infile, which parmed copies to this flag. If it is not present in that line, parmed prepends it. However, this action is taken inside a loop over a list that may be empty. With this update, parmed now checks that this array contains at least an empty string.
Best,
Karl
=> chamberparm's FORCE_FIELD_TYPE should now always contain CHARMM

parmed/formats/pdb.py, parmed/residue.py, test/test_parmed_formats.py
Add the ability to write standardized PDB residue names for amino and nucleic
acid residues. This converts common nicknames for various protomers/tautomers
used by programs like Amber to distinguish between them.
=> Add option to write standard PDB resnames to PDB and CIF files

devtools/travis-ci/install.sh, test/test_openmm_amber.py, test/test_openmm_charmm.py, test/test_openmm_gromacs.py, test/test_openmm_reporters.py
Convert back to using the CPU platform for PME and pull in the openmm-dev
package from conda. See if the recent change to the CPU PME plugin fixes the
weird hangs that I was seeing with Travis *all the time*.
=> Go back to using the CPU platform

parmed/tools/parmed_cmd.py
Catch all errors and print out tracebacks for unexpected ones to aid in
debugging, but don't kick people out.
Fixes #342
=> Avoid kicking interactive users out of the interpreter ever

doc/structure.rst, parmed/structure.py, test/test_parmed_structure.py
It would be silly to make `struct * 10` behave different than `10 * struct` -- not to mention confusing.  So just go ahead and implement `Structure.__rmul__` as the same as `Structure.__mul__`.  Add a test for it and update docs.
Closes #286
=> Make multiplication operator on Structure commutative

doc/structure.rst, parmed/__init__.py, parmed/amber/amberformat.py, parmed/amber/readparm.py, parmed/structure.py, test/test_parmed_charmm.py, test/test_parmed_structure_slicing.py
This makes it so you can use the selection/slicing syntax to obtain a view of the Structure data rather than a copy.  It will let you do something like this:
```Python
struct = pmd.load_file('something.prmtop')
for atom in struct.view[100:200,:]:
atom.charge = 0
```
Closes #278 
cc #272 -- this would work for that code snippet as well
=> Add `Structure.view`

parmed/amber/netcdffiles.py
We don't make much use of the mmap feature here (ParmEd is not particularly
concerned about memory usage in trajectory processing -- other libraries are
optimized for that).
Also make sure that scipy-generated files are opened in 64-bit offset mode.
Fixes #358
=> Open scipy NetCDF files with mmap=False

parmed/formats/registry.py, test/test_parmed_formats.py
Some coordinate file types (e.g., Amber ASCII trajectories) require natom and
hasbox to know whether or not that information is present in the file. Just like
the ``structure`` keyword, these keywords are not required for all coordinate
file types, so let them pass silently if they're not needed, but given.
=> Special-case natom and hasbox keywords in load_file

parmed/formats/pqr.py, test/test_parmed_formats.py
residue.number and atom.number were kept as strings rather than casting them to integers.
=> Fix bug when parsing PQR files

parmed/formats/pqr.py, test/test_openmm_reporters.py, test/test_parmed_formats.py
PQR files are too similar to PDB files to properly distinguish between all variants of both.  So make it so PQR files are *only* detected if it doesn't appear to be a valid PDB file.
=> Make PQR file detection stricter

parmed/residue.py
sets have faster lookups (by key, not by index); things like
```Python
element in collection
```
is O(1) for sets and O(N) for lists.
This also eliminates a duplicate entry in the cation list.
=> Make lists of residue names sets instead of lists

parmed/residue.py, test/test_parmed_residue.py
taken from 
3P4{A,B,C,D} and 1EHZ.
I will update if I see new ones (and the test is not very comprehensive)
scripts:
```python
import parmed as pmd
pdb_list = ['1EHZ',]
standard = set(('A', 'U', 'C', 'G', 'HOH'))
four_letters = ('A', 'U', 'C', 'G')
for pdbidb in pdb_list:
t = pmd.download_PDB(pdbidb)
resset = set(res.name.rstrip() for res in t.residues) - standard
for c in four_letters:
print (c, [x for x in resset if c in x])
```
=> Modified nu residue names

parmed/formats/pdb.py, parmed/formats/pqr.py, parmed/structure.py, test/test_parmed_formats.py
Old (bad) behavior was to write all models with the same coordinates.
=> Fix writing PDB and PQR files with multiple models

parmed/amber/_amberparm.py, parmed/amber/amberformat.py, parmed/gromacs/gromacstop.py, parmed/structure.py, parmed/topologyobjects.py, test/test_parmed_serialization.py
Can now pickle Structure, AmberFormat, and AmberParm and its subclasses.
Still need to check on some others:
This closes #328
=> Implement serialization for a wide array of ParmEd objects

devtools/travis-ci/pyflakes_check.sh, doc/gromacs.rst, parmed/gromacs/gromacstop.py, test/test_parmed_genopen.py, test/test_parmed_gromacs.py, test/test_parmed_serialization.py, test/utils.py
`GromacsTopologyFile.write(combine)` now accepts a list of lists, where the second level of list specifies molecule indices to combine into a single moleculetype.  These indices *must* be consecutive, since otherwise it will desynchronize from the coordinate file.
Closes #435
=> Implements moleculetype combining semantics for GromacsTopologyFile

doc/omm_amber.rst, parmed/openmm/reporters.py
Fixes the problems raised in #446.  This updates the Amber examples to the actual scripts provided with ParmEd as examples.  It also adds in the *correct* exception catching in the destructors of various reporters where an exception is raised during construction (and as a result, not all attributes have been set).
=> Small fixes to docs and destructors

parmed/__init__.py, parmed/gromacs/gromacstop.py, test/files/saved/benzene_cyclohexane_10_500.top
Accidentally swapped charge and mass. It was mainly cosmetic, as these masses
were not used by anything that I'm aware of, but it's still better to print out
compatible topologies.
=> Fix printout of masses in generated GROMACS top files

parmed/__init__.py, parmed/gromacs/gromacstop.py, test/files/159.top, test/test_parmed_gromacs.py
Neither the `__copy__` nor the `__getitem__` functions for `GromacsTopologyFile` were implemented for that object (i.e., it was just calling the underlying function from the inherited `Structure`).  Since `Structure` stores the 1-4 scaling constants either in the dihedrals themselves (in the case of Amber), or in the explicit list of exceptions, ParmEd would never set the `defaults` attribute for the copy (meaning it would just get the default when copying a GromacsTopologyFile).
This broke the `GromacsTopologyFile` copy constructor when you just wanted to print out a new Gromacs topology file (and also broke the selector [], which is used by split under-the-hood).  The reason I didn't catch this before is that the underlying `Structure` still had the correct information -- just in the …
=> Fix misassignment of `defaults` section for GromacsTopologyFile

parmed/tools/actions.py, parmed/tools/parmed_cmd.py
Prevent interpreter from shutting down.
Fixes #462
=> Protect against bad "source" commands

parmed/__init__.py, parmed/amber/_amberparm.py, parmed/structure.py, parmed/tools/actions.py, test/test_format_conversions.py, test/test_parmed_amber.py, test/test_parmedtools_actions.py
This causes problems now that the parm is always rebuilt before writing.
Sometimes we want unit cell vectors even if we don't have solvent...
=> Do not delete box when solvent removed by strip in AmberParm

parmed/charmm/parameters.py, parmed/gromacs/gromacstop.py, parmed/parameters.py, test/test_parmed_charmm.py
This was not always the case, and could cause problems.  Now ParmEd is fully consistent everywhere with respect to storing CMAP types in `ParameterSet` dictionaries.
This also means that the recent fix in #505 will now always be correct.
=> Ensure that cmap_types key is *always* an 8-type tuple in `ParameterSet`

parmed/openmm/parameters.py, test/test_parmed_openmm.py, test/utils.py
Following the discussion in https://github.com/pandegroup/openmm/issues/1298, there is no way for us to break `ffxml` files into separate files for parameters, amino acids, and nucleic acids (and possibly other components) if atom types are based on `resname-atomname` due to the requirement that parameters can only refer to atomtypes that have been defined in the files that have already been read.  Even if the atom classes were set to be AMBER atom types, atom classes are simply expanded into the set of matching atom types that have been defined at the time the parameters are read, so this would not work without major changes to `ForceField`.
See [the OpenMM User Guide](http://docs.openmm.org/6.3.0/userguide/application.html#using-multiple-files), which states:
> If multiple XML files are …
=> Revert to using AMBER atom types in generating OpenMM ffxml atom types

parmed/amber/titratable_residues.py
This should prevent OS- and Python version-dependent differences in cpin file
contents caused effectively by floating-point precision issues.
=> Make cpin output a little more reliable

parmed/openmm/parameters.py, test/test_parmed_openmm.py
Move unsupported error catch to script function, since that's where it will
ultimately be implemented. Also fix 1-4 scaling factor determination so it is
not hard-coded for Amber (and works with any homogenous force field with an
appropriate error message for non-homogenous FFs, like Amber/GLYCAM).
=> Small tweaks to openmm ffxml writing

parmed/structure.py
Support OpenMM versions that require GB parameter conversions and that don't
(because they now do it inside the CustomGBForce subclasses directly).
=> Fix GB support for newer versions of OpenMM

parmed/amber/_chamberparm.py, parmed/structure.py, parmed/tools/actions.py, parmed/topologyobjects.py, test/test_format_conversions.py, test/test_parmed_charmm.py, test/test_parmed_topologyobjects.py
Fixes a few very small bugs (`__contains` -> `__contains__` for two Amoeba topology objects), removes deprecated API features, and significantly improves test coverage, although not fully complete on this module yet.
=> Add tests to improve coverage of topologyobjects

parmed/openmm/parameters.py
Was iterating through keys, but Dihedral Types lists are values in the `dihedral_types` dict,
=> _write_omm_nonbonded fix key/value bug

parmed/gromacs/gromacstop.py, test/test_parmed_gromacs.py
@swails are you in the process of moving over all your testing functions names to snake? I can swap that out real quick too.
=> Respect `parametrize` flag when reading .top files

parmed/topologyobjects.py
Let me know if there's something else fancy happening under the hood but `5` designates a fourier dihedral in Gromacs. These can be interconverted of course but that doesn't appear to be happening (yet!).
=> Correct Gromacs func # for RB torsions

parmed/__init__.py, parmed/gromacs/gromacstop.py, parmed/topologyobjects.py, test/test_parmed_gromacs.py, test/test_parmed_topologyobjects.py
The basic behavior here is that AtomType *can* have a charge, and if an `Atom` has an `atom_type` attribute, but never has a charge set, it will see the charge from its `atom_type`.  However, setting a charge on an `Atom` directly overrides its `atom_type`.
GROMACS parsers now assign the parsed charge to its atom type when reading `[ atom_types ]`.  This should address #544.
@ctk3b -- does this work for you?  What do you think of it?
=> Adds a charge attribute to AtomType

MANIFEST.in
These are never used and should probably ultimately be removed from the repo altogether, but it does have some neat stuff from Lee-Ping that I occasionally still use.
=> Remove GmxTests from MANIFEST.in

parmed/openmm/parameters.py
```type2="%"``` was ```type=2"%"```
=> Fixed equal sign in cmap types

setup.py
This should play nicer with pip (distutils builds are deprecated when installing through pip).  This also lets me use entry points (rather than CL scripts), which will behave correctly on Windows (unlike distutils builds).
=> Use setuptools when available

parmed/openmm/topsystem.py, parmed/openmm/utils.py, parmed/openmm/xmlfile.py, setup.py, test/.coveragerc, test/test_parmed_openmm.py
Also fixes a couple small issues:
- passing an open file handle (instead of a file name) to XmlFile.parse failed
- atom type compression for L-J types was not implemented correctly, although
the resulting systems were correct from a FF perspective. The only side-effect
is that a Structure loaded from an OpenMM System might have had nonbonded type
tables that were larger than they needed to be (and as a result might have had
GPU performance implications for large systems).
=> Add a bunch of tests to the openmm package.

parmed/amber/parameters.py, test/test_parmed_amber.py
As discussed in https://github.com/ParmEd/ParmEd/issues/486#issuecomment-177010286
Can now call `AmberParameterSet(file)` with .lib and .off files in addition to .dat and frcmod.
=> allow reading of .lib files through AmberParameterSet() call

test/test_parmed_amber.py
=> Fix redundant os.path.join in #585

parmed/amber/parameters.py, test/test_parmed_amber.py
As we discussed in https://github.com/ParmEd/ParmEd/issues/486 . 
Not sure if this is the best approach here, what do you think?
=> addAtomTypes only updates atomic number info for types existing in .dat/frcmod // hard-code EP and LP

parmed/amber/parameters.py, parmed/openmm/parameters.py, test/test_parmed_openmm.py
=> Add args to: ignore ions/solvents at leaprc reading, only write out atom types that are used in templates in ffxml

parmed/openmm/parameters.py, test/test_parmed_openmm.py
Not tested yet, just want to show you the idea first.
* Write multiple elements with the same tag - e.g. two references, by having `provenance = {'Reference' : ['reference1', 'reference2']`}
* Write elements with attributes - the Source element, by having:
``` python
provenance = {'Source' : {'Source' : 'leaprc.ff14SB', 'md5hash' : '...', 'sourcePackage' : 'AmberTools', 'sourcePackageVersion' : 15}
```
i.e. pass nested dict, one of the keys has to be identical to the element tag, that becomes the content, rest of keys feed attributes.
=> OpenMM provenance tweaks

parmed/__init__.py, parmed/amber/parameters.py, test/test_parmed_amber.py
See the discussion in choderalab/openmm#7.  This commit should fix that issue.
=> Implement improved processing of parm.dat files when equivalence lines LIE

parmed/gromacs/gromacstop.py
I encountered this error when running a jupyter notebook on a remote server and trying to save a `.top` file.
There seems to be a fundamental issue with `os.getlogin()` (as alluded to in the Python [docs](https://docs.python.org/2/library/os.html?highlight=getlogin#os.getlogin)) and as far as I can tell this is the best work around for posix systems.
See [here](http://code.activestate.com/lists/python-list/288845/) for some more info. If you are interested in a better cross-platform approach, I also found [this](http://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python/842096#842096) suggesting the `getpass` module.
=> Fix "Inappropriate ioctl for device" in .top writer

parmed/charmm/parameters.py
Nothing major but it stumped me for a second when I first tried to load multiple charmm files.
I couldn't find anything [official](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) on how to document `*args`. The sphinx [napoleon](http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_numpy.html) plugin recommends the following but I think we can provide a bit more info.
```
*args
Variable length argument list
```
=> Fix minor inconsistency in docstring

parmed/openmm/parameters.py
Since CharMM uses the negative value for epsilon only to signal that it's indeed an epsilon, we should write out the absolute value for epsilon.
=> absolute value for Epsilon

parmed/structure.py
=> Do not add redundant (meaningless) exceptions for each atom with itself.

parmed/charmm/parameters.py, test/test_parmed_charmm.py
Currently the CHARMM parameter set parsers raise a fatal exception when L-J parameters are set on an atom type that doesn't exist.  This change simply warns when that happens and soldiers on (it will later quit with a KeyError if you try and *use* that atom type).
=> Warn when setting L-J parameters on atom types that don't exist

parmed/openmm/parameters.py
Any advantages / disadvantages to using `!=` or `is not`?
This should fix https://github.com/choderalab/openmm/issues/10
=> do not write double external bonds if head == tail

parmed/openmm/topsystem.py
We were getting warnings like this for molecules containing three-membered rings:
```
/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/openmm/topsystem.py:428: OpenMMWarning: Detected incomplete exceptions. Not supported.
OpenMMWarning)
```
This change fixes the construction of [`bond_graph_exceptions`](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/topsystem.py#L392-L398) to exclude entries where `parmed` thinks an atom should be excluded from itself.
=> Don't add self exceptions to bond graph exceptions

parmed/namd/namdbinfiles.py
Users should never think they need to scale the resulting data since
that is done automatically for them. SCALE_FACTOR being public can lead
to confusion.
=> Make SCALE_FACTOR a private variable in the NAMD parsers

parmed/modeller/residue.py, parmed/openmm/parameters.py, test/test_parmed_openmm.py
Fresh PR for https://github.com/ParmEd/ParmEd/issues/629 + overload support for residue templates (implemented in https://github.com/pandegroup/openmm/pull/1373 and https://github.com/rafwiewiora/openmm/commit/4e9b65cf26f10820f4c46f4fc9dadc32e2264a61 specifically). 
Summary of the overloading for reference:
* residue templates in XML `overload` attribute like such:
``` xml
<Residue name="Ag" overload="1"/>
```
* default is zero, that does not have to be present in the XML
* internal variable called `overloadLevel` so I made it `omm_overloadLevel` in ParmEd
* higher `overloadLevel` wins if names are the same for 'identically matching' templates
* `residue.omm_overloadLevel` will be set for templates in `OpenMMParameterSet` by conversion script
=> Do not write identical residues to OpenMM XML // Add support for omm_overloadLevel for templates

parmed/charmm/parameters.py
I ran into a CharMM stream file where MASS is written as Mass. 
Here's the file:
https://github.com/ChayaSt/Charmm36_FF/blob/master/toppar/stream/misc/toppar_ions_won.str#L31-L95
=> Mass should be case-insensitive

parmed/charmm/parameters.py, parmed/openmm/parameters.py
If the atom type is a dummy atom, leave out element from attributes so that forcefield.py can parse the xml.
=> Leave out element for dummy atom

parmed/__init__.py, parmed/gromacs/gromacstop.py
All the tests except one pass on windows.  (and the failing test is not my fault:)
```
================================== FAILURES ===================================
_____________________ TestRegistry.test_load_file_errors ______________________
self = <test_parmed_formats.TestRegistry testMethod=test_load_file_errors>
def test_load_file_errors(self):
""" Test error handling in load_file """
fn = get_fn('test.file', written=True)
with open(fn, 'w') as f:
pass
os.chmod(fn, int('311', 8))
>       self.assertRaises(IOError, lambda: formats.load_file(fn))
test\test_parmed_formats.py:1934:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test\test_parmed_formats.py:1934: in <lambda>
self.assertRaises(IOError, lambda: formats.load_file(fn))
_ _ _ _ _ _ _ _ _ _ _ …
```
=> Fixed the lack of pwd module on windows

parmed/__init__.py, parmed/charmm/psf.py
See https://simtk.org/forums/viewtopic.php?f=161&t=6512&p=16820#p16820 where Henry van den Bedem reported the same issue for OpenMM (and the PSF parser in OpenMM is an early incarnation of the version I originally wrote for ParmEd).
=> Fixed PSF parsing when negative residue numbers are present.

parmed/charmm/parameters.py
Turns out CharMM has many duplicate residues with different atom types across different force fields that should be compatible. I didn't check yet if the parameters are identical for these atom types, but I thought it's good to get a warning when they get overwritten. I still need to figure out how to handle this. If the parameters are all identical, it shouldn't matter. But if they're not, we might need to write out both and use  overload.
=> Add warning when replacing residues

parmed/__init__.py, setup.py
setuptools.command.clean does not exist. It didn't fail because the exception
catching just made setup.py fall back on distutils even when setuptools was
available.
=> Fix setuptools install

parmed/charmm/psf.py, test/test_parmed_charmm.py
This PR adds the option not to create a deep copy of the ```ParameterSet``` when calling ```load_parameter```. This save substantial time as profiled here: https://github.com/choderalab/torsionfit/pull/25#issuecomment-209653537
=> Added a copy option to load_parameters

parmed/__init__.py, parmed/charmm/psf.py, parmed/scripts.py
Closes #676 
Here's an example of the new behavior.  Using the following command-line:
```
parmed -p tip4p.parm7 -c tip4p.rst7 -p propane.pdb -p tripos9.mol2
```
Gives the following start to the log file:
```
```
=> Add useful information to log file

parmed/formats/pdb.py, parmed/formats/pqr.py, test/test_parmed_formats.py
(and CIF files for the HETATM cards).
This improves compatibility of ParmEd-generated PDB files with both Amber *and*
Tinker, which requires residues like HOH/WAT and ions to be HETATM instead of
ATOM.
Closes #355
=> Add TER card writing and HETATM writing where appropriate in PDB files

parmed/tinker/tinkerfiles.py, test/test_parmed_tinker.py
This fixes atomic number identification for ions, which are identified as single atoms with no bonds.
Closes #482
=> Improve atomic number prediction for XYZ files

parmed/amber/_amberparm.py, test/test_parmed_amber.py
=> Fix issue where nonbonded tables didn't get set following `AmberParm.__getitem__`

parmed/formats/mol2.py, parmed/modeller/residue.py, parmed/topologyobjects.py, test/test_parmed_formats.py
This adds a new attribute "order" to the `Bond` class to remember the bond order.  So far, it's only specified in mol2 files, so this only affects saving mol2 files from residue templates or structures that have been created by parsing a mol2 file.
Whenever bond information is present *without* specifying an order (i.e., every file type *except* mol2 files), a bond order of 1.0 is assumed.
Still needs documentation.  This adds a test, though.
Fixes #691
=> Remember bond order where applicable

parmed/amber/_amberparm.py, test/test_parmed_amber.py
In rare occasions, the Amber prmtop file misassigns some atomic numbers by setting the ATOMIC_NUMBER to -1.  This PR identifies those cases and replaces -1 with the atomic number guessed by finding the element with the closest mass.
This fixes an issue in hydrogen mass repartitioning reported by Alexey and Adrian in an email to me.
=> Improve atomic number assignment in Amber prmtop file

parmed/charmm/parameters.py
When writing a CHARMM parameter file, I encountered an `AttibuteError` (see below) which I could track to lines 473 + 474 in file `parmed/charmm/parameters.py`: `angle_type` was stored in `self.bond_types` instead of `self.angle_types`.
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-6-fa81f7d84e85> in <module>()
8     print stream
9     params.read_stream_file(stream)
---> 10     params.write(par='joined.prm')
/Users/chris/git/ParmEd/parmed/charmm/parameters.py in write(self, top, par, str)
981             f.write('*>>>> CHARMM Parameter file generated by ParmEd <<<<\n')
982             f.write('*\n\n')
--> 983             self._write_par_to(f)
984             if ownhandle: f.close()
985         if str is not None: …
```
=> use self.angle_types instead of self.bond_types when replacing angle parameters

parmed/amber/offlib.py, test/files/saved/test.off
- Write box angle in degrees instead of radians
- Make the connect arrays first and last atoms in residue rather than both
first atoms
- Update imaging atom for multi-residue collections so it's not always in
the first residue.
Fixes issue Bill Miller raised when an OFF file of a cyclohexane solvent box segfaulted tleap.
=> Fix a few small issues with writing solvent boxes in OFF files:

devtools/travis-ci/install.sh, parmed/amber/netcdffiles.py, test/test_parmed_netcdf.py
This is done because writing netCDF4 files is *way* faster than in pure Python
with scipy's version. This will fix the horrific performance issues seen with
the NetCDFReporter when running OpenMM GPU simulations.
Fixes #619
=> Switch to using netCDF4 to write NetCDF files if it's available

parmed/gromacs/gromacstop.py
Fixes #729 
Might require some py2/3 compatibility tweaks
=> Escape strings in gromacs .top comment

parmed/structure.py
The amber custom gbsa forces now require calling `finalize` before use. This change adds this call, swallowing the resulting exception that occurs with older versions of openmm.
The call to finalize is needed because the optimized versions of `GBn` and `GBn2` cache the atom parameters in order to upload only the necessary values of `d0` and `m0`. The particles are only added to the force when `finalize` is called.
=> Call finalize on gbsa forces

devtools/travis-ci/install.sh, parmed/structure.py, test/test_parmed_visualization.py
I think it's convenient to add this. What do you think? 
```python
parm.visualize()
parm[':1-20'].visualize()
```
There is no test yet since I am not sure if you are ok with this PR.
Another advantage is amber user can use `parmed` to visualize netcdf trajectory (and others) on window.
=> add visualization

parmed/amber/offlib.py
The connection list in OFF files is only 6 characters, and the 1st two elements
are reserved for the head and tail atoms. In very rare cases where there are too
many connections, this may throw an IndexError. This fixes the IndexError by not
writing the atoms that don't "fit" in the line.
=> Fix OFF writing for residues with many connections

parmed/tools/actions.py, test/test_parmedtools_actions.py
This is necessary to get SETTLE to work on Amber with the default values of
WATNAM and OWTNM. (these can always be changed to TIP3 and OH2 to get SETTLE to
work regardless).
Addresses suggestion by @dacase
=> Have the chamber action change water names to WAT and O 

parmed/formats/pdb.py, test/test_parmed_formats.py
The mistake was very dumb.  I was parsing the insertion code from ANISOU records in the 28th character field instead of the 27th.
This might also fix another bug when two residues with different insertion codes come right after each other but are the same kind of residue.
=> Fix erroneous warnings with ANISOU records

parmed/amber/_amberparm.py
I encountered this while playing with one of the InterMol amber [input files](https://github.com/shirtsgroup/InterMol/blob/master/intermol/tests/amber/stress_tests/solv/solv.rst7). This fix appears to work for my use case but I am not very familiar with the amber portions of ParmEd. Will this interfere with anything else?
=> Read velocities from amber files if available

parmed/formats/pdb.py, parmed/residue.py, test/test_parmed_formats.py
Reported by @dacase:
The _standarize_resname() funtion in parmed/formats/pdb.py (in the master
branch at SDSC)  does this:
```python
def _standardize_resname(resname):
""" Looks up a standardized residue name for the given resname """
try:
return AminoAcidResidue.get(resname).abbr, False
except KeyError:
try:
return RNAResidue.get(resname).abbr, False
except KeyError:
try:
return DNAResidue.get(resname).abbr, False
except KeyError:
return resname, True
```
Problem is that the AminoAcidResidue class knows that "G" is a "symbol"
for GLY.  So if the above code sees "G" as a resname, it notes that the key
length is 1, thinks resname is a symbol, and returns the glycine residue.
So write_pdb with standard_resnames=True fails when given RNA, since "G" gets
assigned to glycine before having a …
=> Fix writing PDB file with standard residue names

parmed/amber/mask.py, parmed/tools/actions.py, test/test_parmed_amber.py
- Add documentation to printBonds|Angles|Dihedrals giving details about
the units that are used for the measurements
- Add a test for the fix
=> Fix mask parsing errors when there is leading or trailing whitespace.

parmed/amber/_amberparm.py, parmed/amber/amberformat.py
The issue is that the `AmberParm.__copy__` method did not copy
coordinates. This commit fixes that.
Fixes #793
=> Fix missing coordinates with AmberParm

parmed/formats/pdb.py, test/test_parmed_formats.py
The code does not work yet. Can you help? :D 
```python
import parmed as pmd
parm = pmd.load_file('SCM_A.pdb')
print(parm.space_group)
parm.save('test.cif', overwrite=True)
print(pmd.load_file('test.cif').space_group)
```
output
```
P 1 21 1
P 1
```
=> add space_group to cif

parmed/structure.py, test/test_parmed_formats.py
=> Make sure TER cards do not go missing upon Structure copying

devtools/travis-ci/install.sh, parmed/openmm/topsystem.py, test/test_format_conversions.py, test/test_parmed_openmm.py, test/utils.py
When loading an OpenMM `Topology` into `Structure`, `AtomType` names are
autogenerated and types with equivalent LJ params are combined. This
PR adds an option to instead take the `AtomType`'s name from the optional
Openmm `Atom.id` attribute instead.
This change should not affect any previous behavior.
=> Add option to name types based on OpenMM Atom.id

parmed/formats/pdb.py, test/test_parmed_formats.py
This commit adds a test to make sure that negative indices are respected
in PDB file writing. In particular, negative residue numbers are used
somewhat frequently (especially in RNA systems), and the current code
just takes the % 10000 (for residues) and % 100000 (for atoms). Which
yields very weird behavior.
Also add a test for this.
=> Fix negative index writing in PDB files

parmed/gromacs/gromacstop.py
Currently, when parsing gromacs topology files, you will have access to the parameter set via the `parameterset` property on `GromacsTopologyFile` even when there is no `[molecules]` section. However, the structure object (the result of parsing sections like `[atoms]`) gets lost unless you add a `[molecules]` sections to your topology file. I think it would be nice to store the parsed structures as `molecules` property just like `parameterset`.
I understand that it's not really necessary for topology *modification*, but I personally am using ParmEd only as a parameter/topology **reader**. For instance, [VirtualChemistry](http://virtualchemistry.org/ff.php) GROMACS topologies do not have the `[molecules]` section which makes it a bit difficult to use ParmEd for extracting all the …
=> Keep molecules when there is no structure content

parmed/charmm/parameters.py
This commit adds the GEOM keyword to the nonbonded card in the CHARMM
parameter file if geometric combining rule is requested.
=> Fix CHARMM geometric combining rules

parmed/openmm/parameters.py
Last thing necessary for the Amber FF conversion - this adds the `ordering='amber'` attribute (and @ChayaSt @jchodera will need to use it to add `ordering='charmm'` to their CHARMM ffxml) to the `PeriodicTorsionForce` element.
cc https://github.com/pandegroup/openmm/pull/1560
=> Add improper_dihedrals_ordering parameter for Amber FF conversion

devtools/ci/travis/install.sh, parmed/charmm/parameters.py, parmed/exceptions.py, parmed/modeller/residue.py, parmed/openmm/parameters.py, parmed/parameters.py, test/test_parmed_charmm.py, test/test_parmed_modeller.py, test/test_parmed_openmm.py
This PR improves support for reading CHARMM patches and adds support for writing them in [OpenMM `ffxml` format](http://docs.openmm.org/development/userguide/application.html#patches).
Patches are stored in the `ParameterSet.patches` field as an `OrderedDict` using an improved version of the `PatchTemplate` structure.
The `ResidueTemplate.apply_patch()` convenience function can be used to apply a `PatchTemplate` to generate a modified residue template. An exception is thrown unless
* all atoms to be changed or deleted are present
* all bonds to be added involve extant atoms
* the resulting net charge of the `ResidueTemplate` is integral (to a specified precision)
* the bond graph has exactly one connected component
The last criteria introduces an optional dependency on `NetworkX`, which …
=> Improved CHARMM patch reading and support for OpenMM ffxml patch writing

CMakeLists.txt
This is a small change to put ParmEd into the "python" sub-package.
=> Add ParmEd to Python CMake component

parmed/rosetta/pose.py
I was having an issue where trying to convert PyRosetta4 Pose objects into ParmEd structures was making my system hang. This appears to be caused by calling the `tuple` function on the `pyrosetta.rosetta.numeric.xyzVector_double_t` containing the atomic coordinates. The small change in the code below fixes this.
I also updated the import to the new style (importing from rosetta rather than pyrosetta is marked to become deprecated and produces a warning).
=> Fix for PyRosetta4 Pose to ParmEd structure conversion

parmed/modeller/residue.py, parmed/openmm/parameters.py, parmed/topologyobjects.py, test/test_parmed_modeller.py, test/test_parmed_openmm.py, test/test_parmed_topologyobjects.py
This PR partially addresses https://github.com/ParmEd/ParmEd/issues/941
Currently, the [`test_write_xml_parameters_charmm`](https://github.com/ParmEd/ParmEd/blob/master/test/test_parmed_openmm.py#L612-L633) will fail because, once H-H bonds are removed, there are now two identical water residue templates in [`toppar_water_ions.str`](https://github.com/ParmEd/ParmEd/blob/master/test/files/toppar_water_ions.str#L65-L87), causing OpenMM's `ForceField` to throw an exception. This means that there is no way for ParmEd to correctly read CHARMM parameter sets and write them to OpenMM if they contain duplicate waters, as the standard `toppar_water_ions.str` does. 
To fix this, I am currently presuming we will need to add the capability to specify which residue templates to omit when reading a …
=> Have OpenMMParameterSet remove non-chemical H-H bonds from water upon creation

parmed/openmm/parameters.py
cc: https://github.com/choderalab/openmm-forcefields/pull/61#issuecomment-365052830
CMAP forces were incorrectly being written to OpenMM ffxml file with the misspelled tag `<CMapTorsionForce>` instead of the correct `<CMAPTorsionForce>` used [here](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2278). 
I'm trying to think of an appropriate test to make sure that all tags are correctly handled. 
A force-by-force breakdown could work, but is difficult to manage.
=> Fix typo in OpenMM ffxml tag name "CMAPTorsionForce"

parmed/charmm/parameters.py, parmed/modeller/residue.py, parmed/openmm/parameters.py, test/test_parmed_modeller.py
This PR ensures that patches and residues are processed and compared in deterministic order---the same order as read in. 
This allows us to avoid issues like [this](https://github.com/choderalab/openmm-forcefields/pull/61#issuecomment-365117418) where patches are compared against random base residues for determining what should be added/deleted in a patch.
=> Ensure processing of CHARMM residues and patches in deterministic order

setup.py
This PR integrates test runs into `setup.py`:
python setup.py -v nosetests
This has [some advantages](https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner), like to ensure that the same version of Python is used for both installation and testing.
=> Add test_suite to setup.py

parmed/amber/netcdffiles.py
=> netCDF4's flush() is really sync() -- so call that if it's an attribute

parmed/openmm/parameters.py, test/files/molecule.frcmod, test/files/molecule.mol2, test/test_parmed_openmm.py
Fixes #977 and https://github.com/pandegroup/openmm/issues/2047
This PR contains three bugfixes:
* Prune duplicate patches when converting to `OpenMMParameterSet` (https://github.com/pandegroup/openmm/issues/2047)
* The addition of a `remediate_residues` flag to `parmed.openmm.OpenMMParameterSet.from_parameterset()` that allows `openmoltools` to skip the step where residues without defined atom types are discarded (#977)
* Minor performance improvement via deleting unnecessary code
=> Bugfix necessary to allow openmoltools to work with recent ParmEd

parmed/formats/pdb.py, test/test_parmed_formats.py
HETATM tags in PDB can cause problems for certain use cases. For example NAMD doesn't recognise them and raises errors. Adding an option to `write_pdb` to optionally use `ATOM  ` instead of `HETATM` fixes this problem. The default is still the same as was before.
=> Add flag to optionally write HETATM tags in PDBs

src/_rdparm.cpp
I know this is pretty minor but it always bothers me when I see it in the build output.  Now `m` has a use in the python 3 version of the code so it won't trigger a warning.
=> Fix unused variable warning in rdparm.cpp

parmed/formats/pdb.py
PDB files created by refmac often have LINKR records, which is a variant of the "official" PDB LINK record.  Since refmac files are very common
(e.g. all of pdb_redo uses this program), parmed should not reject a
file as PDB format just because it has a LINKR record.  This change would be in
line with other non-standard record types that are already allowed.
=> allow LINKR records in PDB files

parmed/openmm/parameters.py
There are cases where it makes sense for a ffXML file to contain multiple templates that will be considered identical according to OpenMM's topology-matching approach. The most obvious use-case is stereoisomers - sugars in particular become a huge problem under the default scheme. Another is metal ions of the same element but different valency (for those brave enough to actually use them).
=> Option to keep duplicate templates when writing OpenMM ffXML

parmed/__init__.py
Hi,
I have not used parmed for awhile and here is the issue I met.
I want to use `read_PDB` function to create a Structure from StringIO (`load_file` does not offer that).
I used `read_pdb` at first and realized that it did not exists. Can we make an alias here (I guess it's no harm).
=> add alias read_pdb, read_cif, download_dpb, download_cif

parmed/formats/pdb.py, parmed/gromacs/gromacstop.py, parmed/periodic_table.py, parmed/structure.py, parmed/tinker/parameterfile.py, parmed/topologyobjects.py, test/test_parmed_formats.py, test/test_parmed_gromacs.py
It now essentially discards any efforts made to conform to the PDB
standard while parsing PDB files that very clearly break that standard
(e.g., by overflowing the atom and residue index fields).
No attempt is made anymore to decode differently-encoded residue or atom
numbers (all attempts were always sequential, anyway).
Nobody should be negatively impacted by this change, and it dramatically
simplifies the routine and fixes other deficiencies. That is, it is now
a more-compliant parser than it was for PDB files that obey the
standard.
Now it's time to spend a bajillion years debugging :-/
Fixes #1013
=> Complete overhaul of the PDB parsing routines.

parmed/charmm/parameters.py
Even though the residue would be marked to skip, upon encountering the COLINEAR lonepair type the parser tries to keep going and fails.
Now top_all36_cgenff.rtf can be parsed for chamber actions.
=> Break when parsing unsupported lonepairs

parmed/amber/parameters.py, setup.py
I'm suggesting this change because I'm getting the following
```sh
<...>/venv/lib/python3.7/site-packages/parmed/amber/parameters.py:10: DeprecationWarning:
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
whenever I'm running our test suite over at https://github.com/plotly/dash-bio ;)
=> Fix DeprecationWarning when importing ABCs

parmed/tools/changeradii.py
The current radius is neither the actual Bondi radius (1.75), nor the value used in leap (1.7)
=> Fix Cl Bondi radius to match leap

parmed/openmm/parameters.py
Allows writing of FFXML files to go ahead using the standard Python XML library if lxml is not installed. Probably slightly slower for very big forcefields, but the result is functionally and cosmetically essentially identical apart from the insertion of `<?xml version="1.0" ?>` as the first line (which could easily be stripped, of course - but it appears harmless).
Note: this seems to make the @needs_lxml decorator superfluous.
=> Fall back to stdlib xml if lxml not available

parmed/openmm/topsystem.py, test/test_parmed_openmm.py
In https://github.com/openforcefield/openforcefield/issues/580 (well, everywhere using the SMIRNOFF specification, but it's not always fatal), uniqueness of valence terms based on the atom types they are built off of is not guaranteed. This is not _usually_ a problem since you typically only need the relevant parameters and atom types as part of the valence term (i.e. the length and force constant of a bond and the atom indices - but not atom types! - of the two atoms involved). But some of the bookkeepping does rely on that; we were encountering an issue with atom types being stored as dictionary keys. One approach would be to change that behavior, but this sort of thing is probably going to crop up elsewhere. A not-very-performant but catch-all solution is to make each atom have its own …
=> Optionally don't de-duplicate matching atom types in OpenMM conversion

parmed/periodic_table.py
I noticed that the newest 6 elements were still listed as their predicted forms, so I updated them. The updated masses came from NIST (https://www.nist.gov/pml/periodic-table-elements).
=> Update periodic_table to 2018 IUPAC

parmed/tinker/parameterfile.py
For some very small molecules, `'strbnd'` may not exist in parameter files, so allow fall-through if this is the case.
=> Allow 'strbnd' to be optional for AMOEBA Parameters

parmed/parameters.py
I used the topology converted from PSF to the gromacs format but the
simulation crashed, and after checking the topology file I found the
epsilon and sigma were wrong. It seems PR #1097 only partially changed
the order of assignment of NBFIX. This commit should fix the issue.
=> Fix the order of assignment of the NBFIX terms.

.github/workflows/Test.yaml, README.md, devtools/ci/install.sh, parmed/formats/registry.py, test/test_format_conversions.py, test/test_openmm_amber.py, test/test_openmm_amber_forces.py, test/test_openmm_charmm.py, test/test_openmm_gromacs.py, test/test_openmm_reporters.py, test/test_parmed_amber.py, test/test_parmed_charmm.py, test/test_parmed_cif.py, test/test_parmed_formats.py, test/test_parmed_genopen.py, test/test_parmed_gromacs.py, test/test_parmed_modeller.py, test/test_parmed_netcdf.py, test/test_parmed_openmm.py, test/test_parmed_pandas.py, test/test_parmed_parameterset.py, test/test_parmed_rdkit.py, test/test_parmed_residue.py, test/test_parmed_rosetta.py, test/test_parmed_structure.py, test/test_parmed_tinker.py, test/test_parmed_unit.py, test/test_parmedtools_actions.py, test/utils.py
Parallel testing didn't work because all tests wrote to the same
directory and tests would clobber each others' files. This reworks the
FileIOTestCase so that it creates a unique temporary directory for each
test case that gets run, ensuring that no two test cases could possibly
try to write to the same file.
This should substantially improve the test throughput via `py.test -n 4`
using the pytest-xdist plugin.
=> Allow multiple tests to run at once

parmed/modeller/residue.py
This PR makes a minor modification to how CHARMM patch compatibility is checked, and raises an exception if a patch results in all atoms and bonds being removed from a residue template.
=> Check to make sure CHARMM patch doesn't create empty residue

parmed/topologyobjects.py
**Bug**: 
`self._mass` seems to be undefined in the [Atom](https://github.com/ParmEd/ParmEd/blob/master/parmed/topologyobjects.py#L232) class. Therefore, calling [Atom.umass](https://github.com/ParmEd/ParmEd/blob/master/parmed/topologyobjects.py#L727) raises an AttributeError.
**Fix**: 
Replace `self._mass` with `self.mass`
=> Bug in Atom.umass

parmed/gromacs/gromacsgro.py
In the [GromacsGroFile.write](https://github.com/Andrew-AbiMansour/ParmEd/blob/master/parmed/gromacs/gromacsgro.py#L196) method, there's a logical bug in the way the box is estimated from `struct.coordinates` when it is undefined (incorrect dimension is used).
=> fix wrong dim in box estimation

parmed/structure.py
In [parmed.structure.Structure._ _repr_ _](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L293), parameterization is inferred from bonds/bond types. However, for a system of non-bonded parameterized atoms, Structure appears unparameterized. An improvement is suggested here based on atom types.
=> Improving parameterized inferrence

parmed/topologyobjects.py
The `funct` property in the [Dihedral](https://github.com/ParmEd/ParmEd/blob/master/parmed/topologyobjects.py#L2138) class can return incorrect `self._funct` when `self.type` is `DihedralType`. This ensures `Dihedral.funct` checks for `DihedralType` and subsequently returns 1.
=> missing check for DihedralType in Dihedral.funct

parmed/rdkit/rdkit.py, test/test_parmed_rdkit.py
Previously, if a user decided to use `parmed.rdkit.load_smiles` to
generate a `parmed` structure, no explicit hydrogens are added to the
structure, this can be an issue if trying to generate hydrocarbon
systems.
This PR leverages the built-in `rdkit` method `rdkit.Chem.AddHs` to generate explicit
hydrogens for an rdkit mol. An additional boolean flag: `hydrogens=True` has been added to this method. Since this could break others' workflows, the default value is `False` to comply with current functionality.
=> Add explicit hydrogens when loading in SMILES

parmed/utils/__init__.py
Fixes #1175 
It seems there may be a couple extra calls to _set_owner than just once per atom, so make sure we grow the recursion limit enough for systems with >1000 atoms all in the same molecule.
=> Bump recursion limit

parmed/openmm/parameters.py
When I implemented unscaled 1-4 interactions in #1149, I based it on the assumption that pairs could be classified based just on the types of the two interacting atoms, ignoring the two other atoms that connect them.  This turns out to be wrong.  For example, O-C-CX-H1 is an ordinary backbone torsion that uses standard scaling factors.  By O-C-Cg-H1 is a GLYCAM torsion that should be unscaled.  You need to consider all four atoms to tell the difference.  This changes it to do that.
=> Base unscaled pairs on all atoms in a torsion

parmed/structure.py
support future namespace change in openMM while keeping things backwards compatible (#1176)
=> Fix ParmEd 3.4 to work with OpenMM 7.6

parmed/tools/actions.py, test/test_parmedtools_actions.py
This is a draft implementation of the two-tier mass repartitioning
strategy recently published by the Sugita group. The main change is that
an additional "alternate" target hydrogen mass is supplied for hydrogens
that are connected to a ring. The complete strategy proposed for AMBER
force fields is:
1. reduce the target mass from 3 x 1.008 to 2.5 x 1.008
2. use an alternate target mass of 2 x 1.008
Changes to the code:
- A new optional keyword `altmass` has been added to the HMassRepartition
action that supplies the alternative mass.
- A quick scheme to produce rdkit mol objects from single-residue ParmEd
molecules has been added so that we can access the IsInRing() method for
determining which atoms are in rings.
Things to improve:
The use of rdkit molecules seems to work fine in …
=> Prototype for heterogenous mass repartitioning

parmed/openmm/parameters.py, parmed/utils/__init__.py
@peastman and I have been working on converting the AMBER glycam forcefield (`GLYCAM_06j-1`) into a ffxml for the OpenMM ecosystem -- we have the conversion pipeline working now (after making a number of changes to Parmed, OpenMM, and soon Openmmforcefields), but there is one more ParmEd fix that I had to use for the conversion pipeline that has not been pushed.
After generating the ffxml and upon trying to create a system for a glycosylated protein, I was getting errors like :
```
ValueError: No template found for residue 197 (UYB). The set of atoms matches UYB, but the bonds are different.
```
This was because the ExternalBonds in the ff templates were not correct. In the converted ffxml, for the UYB residue, I was seeing:
```
<ExternalBond atomName="C1"/>
<ExternalBond atomName="O4"/> …
```
=> Perceive external bonds (necessary for glycam ffxml conversion)

test/test_parmed_parameterset.py
TL;DR - Test nbfix_symmetry uses a topology file from OpenFF, which, Gromacs
has.  Without any of the Gromacs data paths, the test fails.  With the
Gromacs data paths, the tests pass.
It might be that nbfix_symmetry has nothing to do with Gromacs, and a better "fix" would be using a topology file without the Gromacs dependency.  I just don't know if that is the case.
Super long story - 
---
No local GROMACS or system GROMACS, the test `test_parmed_parameterset.py::TestParameterSet::test_nbfix_symmetry` fails
```
(apps3) [thomas.watson@stxfrontend001 ParmEd.stx](master)$ env | grep GMX 
(apps3) [thomas.watson@stxfrontend001 ParmEd.stx](master)$ 
(apps3) [thomas.watson@stxfrontend001 ParmEd.stx](master)$ pytest test/test_parmed_parameterset.py::TestParameterSet::test_nbfix_symmetry …
```
=> nbfix_symmetry - gromacs test skip

parmed/gromacs/gromacstop.py
I fix the issue https://github.com/ParmEd/ParmEd/issues/1153. I tested it and it works correctly. In addition, it does not imply severe modifications that must be extensively tested. I hope it helps
Mario S.
=> reading gromacs topologies with insertion codes fixed

parmed/amber/_amberparm.py, test/test_parmed_amber.py
AmberParm.from_structure would fail when converting a topology of some sort that contained only a CMAP, despite this being a now-supported potential term in canonical Amber topology files.
This was already properly supported when *reading* Amber topology files, but not when converting from another format.  This adds a test and fixes that shortcoming.
Fixes #1228
=> Fix AmberParm.from_structure with CMAPs

parmed/amber/_amberparm.py, test/test_parmed_amber.py
Same as #1233, but for the v3.4 branch.
=> Fix AmberParm.from_structure with CMAPs v3.4

parmed/formats/mol2.py
Some programs such as MDAnalysis with generate mol2 files with blank lines between the ATOM BOND and SUBSTRUCTURE sections.
Loading these with  `parmed.load_file` results in `IndexError: list index out of range`. See example file: [l_H22.txt](https://github.com/ParmEd/ParmEd/files/9244102/l_H22.txt)
I think the blank lines are in spec and there has been some discussions here: https://github.com/MDAnalysis/mdanalysis/issues/3747
This PR adds a small change to mol2 parser that continues on blank lines and this allows the file to be loaded. Please let me know if there is a better solution or I can do something different.
Cheers,
Alex
=> Ignore blank lines in mol2

setup.py
Python support has been restricted to Python v3.8 and newer, but `python_requires` is not set. Thus, the new version of ParmEd will still be installed when one use `pip` to install ParmEd on an older Python version. By setting `python_requires`, pip with old Python versions will not install the new version of ParmEd.
=> set `python_requires` to `>=3.8`

parmed/structure.py
Fix #1289. Basically switch out all the `copy()` call with `deepcopy()` in `parmed.Structure.copy()` function, ensuring that nothing is accidentally copied by reference.
=> switch out copy with deepcopy for structure.copy() method

parmed/tools/simulations/openmm.py
Closes #1301 by calling the coordinate array from the Rst7 object.
=> Fix bug with adding positional restraints for OpenMM (ParmEd#1301)

parmed/tools/simulations/openmm.py
There was a spurious argument in the `RestartReporter` function call for OpenMM minimization causing the error:
>    TypeError: __init__() got multiple values for argument 'write_velocities'
Getting rid of the `parm.ptr('natom')` argument resolves the error and brings the function in line with what is written to the script file (lines 553-554).
=> Fix bug with restart reporter for OpenMM minimization

parmed/amber/mdin/cntrl.py, parmed/amber/mdin/gbnsr6.py, parmed/amber/mdin/mdin.py, parmed/amber/mdin/rism.py, test/test_parmed_amber.py
This was left unimplemented from the v3.4 branch. Like the last time, I have made the modifications so that the old and the new work and added the test. I wanted to have done it yesterday so it would go out in v4.1.0, but the remote on GitHub had problems, so I could not do anything. Let me know your comments.
=> Added 3D-RISM and GBNSR6 to mdin configuration

parmed/tools/simulations/openmm.py
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [openmm.py](https://github.com/ParmEd/ParmEd/blob/master/parmed/tools/simulations/openmm.py#L820), there is a method that creates a temporary file using an unsafe API `mktemp`. The use of this method is discouraged in the [Python documentation](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp). iCR suggested that a temporary file should be created using `mkstemp` which is a [safe API](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp). iCR replaced the usage of mktemp with `mkstemp`.
- [POC - Improper Method Call - python - mktemp.mp4](https://drive.google.com/file/d/16YKuKgv7iItWcac2biRyi2Cm8upJ3HP_/view?usp=share_link)
- [MISC - Python - Taking a peek under the …
=> Fixed Improper Method Call: Replaced `mktemp`

parmed/amber/parameters.py, parmed/formats/pdbx/PdbxReader.py
Fix the following warnings:
```
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/parmed/formats/pdbx/PdbxReader.py:329: SyntaxWarning: invalid escape sequence '\S'
"(?:_(.+?)[.](\S+))"               "|"  # _category.attribute
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/parmed/formats/pdbx/PdbxReader.py:331: SyntaxWarning: invalid escape sequence '\s'
"(?:['](.*?)(?:[']\s|[']$))"       "|"  # single quoted strings
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/parmed/formats/pdbx/PdbxReader.py:332: SyntaxWarning: invalid escape sequence '\s'
"(?:[\"](.*?)(?:[\"]\s|[\"]$))"    "|"  # double quoted strings
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/parmed/formats/pdbx/PdbxReader.py:334: SyntaxWarning: …
```
=> fix `SyntaxWarning: invalid escape sequence`

.github/workflows/Test.yaml, devtools/environment-dev.yaml, test/test_parmed_openmm.py
A project I'm working on is looking at adding testing and support for python 3.13. Parmed is one of the dependencies that can't be installed via conda-forge with python 3.13. I played around with installing from source along with python 3.13, and everything seems to work correctly after bumping up the version of `rdkit` in the `environment-dev.yaml` file. I figured it would be worth making a PR that includes this change and adds python 3.13 to the test matrix.
=> Update dev environment and add testing for python 3.13

parmed/formats/pdb.py, parmed/utils/netcdf.py, test/test_parmed_genopen.py
`numpy.compat` has been deprecated in numpy 2 and will be released in future versions. To prevent this from breaking ParmEd, `asbytes` and `asstr` have been implemented in place in the `parmed/utls/netcdf.py` file.
=> Resolve issue/1386, fix `numpy.compat` deprecation warning
