ParmEd/ParmEd

chemistry/structure.py
Eliminate the separate renumber and non-renumber loops and consolidate them all
into a single loop. This was definitely a premature optimization -- the loop
unrolling doesn't lead to any measurable writing performance boost (and writing
is already very fast compared to reading).
=> Simplify PDB writing code

chemistry/structure.py, test/test_chemistry_structure.py
Atom numbers are assigned incrementally from that point on.
=> Fix PDB parsing when atom numbers go to ***** before switching to hexadecimal

chemistry/amber/_amberparm.py, chemistry/charmm/psf.py, chemistry/structure.py, chemistry/topologyobjects.py, test/test_chemistry_structure.py, test/test_chemistry_topologyobjects.py
=> Add an "add_atom" command directly to Structure

ParmedTools/ParmedActions.py, ParmedTools/gui/_guiactions.py, test/test_parmedtools_actions.py
Add PDB and CIF writers to the ParmEd interpreter.
=> Interpreter

ParmedTools/ParmedActions.py, ParmedTools/add1264.py
Fixes an issue in add12_6_4 that Pengfei fixed awhile ago, but I inadvertently
reversed (not sure how that happened). Also updates add12_6_4 to add parameters
for monovalent, trivalent, and tetravalent ions.
=> Changes from Pengfei

test/test_openmm_amber.py, test/test_openmm_charmm.py, test/test_openmm_reporters.py
Seems that storing all of the prmtops in the header is hovering dangerously close to the memory limit.  Load those separately in each test.  It will make the tests a bit longer, but at least it should pass.
=> The gc didn't work.  

.travis.yml, devtools/travis-ci/install.sh, test/files/saved/test_nonpy.off, test/test_parmedtools_actions.py
Particularly with respect to conda. Now that I've used conda a bit more, I
(think I) understand a bit better what to do. Still a bit different, since the
test suite is not a submodule that can be executed directly via nose like mdtraj
is.
=> Try to bring ParmEd's Travis-CI more in line with what mdtraj does

chemistry/amber/_amberparm.py, chemistry/amber/_chamberparm.py, chemistry/amber/_tinkerparm.py
This uses a trick I learned recently.  Basically, you can replace:
```
for i in range(0, 3*ptr, 3):
x = some_list[i]
y = some_list[i+1]
z = some_list[i+2]
... something with x, y, and z
```
with
```
it = iter(some_list)
for x, y, z in zip(it, it, it):
... something with x, y, and z
```
=> Slight perf improvement for AmberParm parsing

chemistry/topologyobjects.py, test/test_chemistry_topologyobjects.py
=> Register 'remove' as a changing method on a TrackedList

chemistry/__init__.py, chemistry/amber/_amberparm.py, chemistry/charmm/charmmcrds.py, chemistry/structure.py, chemistry/vec3.py, test/test_chemistry_formats.py
I suspect this is the culprit in pandegroup/openmm#891
=> Use Vec3 instead of tuples for `positions` for better OMM compatibility

chemistry/parameters.py, test/test_chemistry_structure.py
Should fix Python 3 test failures.
=> Gromacs support

chemistry/amber/_tinkerparm.py, chemistry/gromacs/gromacstop.py, chemistry/parameters.py, chemistry/structure.py, chemistry/topologyobjects.py, test/test_chemistry_structure.py
Opening up another PR here to get these issues worked out.
I'm getting a couple of the OpenMM Gromacs tests failing now, still need to investigate.
=> [WIP] Attempt to support [ pairs ] and [ pairtypes ] sections of Gromacs top files

ParmedTools/gui/_guiactions.py
This works also in Python 2.6 and 2.7, **not** in 2.5
=> Python 3 compatible except syntax

README.md
=> Add docs to README.

parmed/scripts.py, parmed/tools/actions.py, parmed/tools/simulations/openmm.py
Situation: I can not use parmed.py from another user's folder (got permission error).
=> parmed hn: fix permission deny for logging + py3 compat for exception

doc/index.rst
Add Getting Started with some common examples.
=> Add to docs

parmed/__init__.py, parmed/formats/pdb.py, setup.py, test/test_parmed_formats.py
This commit adds the ability to download PDB or mmCIF files by 4-letter PDB ID.
=> Add ability to download PDB and/or CIF files from wwPDB

setup.py
Also delete parmed.pyc and xparmed.pyc if they were created (e.g., by erroneously trying to import them at some point).
=> Make sure parmed.py and xparmed.py are deleted where they can be found

parmed/structure.py
=> Indicate whether unit cell is triclinic or orthogonal in Structure.__repr__

parmed/formats/pdb.py, test/test_parmed_formats.py
Added a "saveto" argument
Fixes #196
=> Add the ability to save a raw copy of a downloaded PDB

parmed/modeller/residue.py, parmed/unit/quantity.py, test/test_parmed_modeller.py
Also adds a test for this functionality.
=> Add a to_dataframe method on ResidueTemplate

parmed/gromacs/gromacsgro.py
=> Fix potential overflows in GRO writing.

parmed/__init__.py
=> Update version number.

parmed/__init__.py
Fixes #217 
Thanks @hainm for the heads-up!
=> Do not import residues.* into the parmed namespace.

parmed/__init__.py
=> Import tools into the top-level parmed namespace.

parmed/scripts.py, parmed/tools/exceptions.py, parmed/tools/gui/guiactions.py, parmed/tools/gui/guitools.py, scripts/xparmed
=> Fixes and tweaks to xparmed

parmed/topologyobjects.py
=> Make the TrackedList __repr__ more useful

parmed/amber/amberformat.py
=> Add __repr__ to FortranFormat

parmed/amber/_amberparm.py, parmed/tools/actions.py, test/files/4lzt_NoNO3.pdb, test/test_parmedtools_actions.py
The changes were not getting propagated everywhere they needed to be.  This adds the failing test revealing the bug and fixes it.
=> Fix bug in addPDB action

parmed/tools/parmlist.py, test/test_parmedtools_parmlist.py
Also adds a test for adding mol2 files to a ParmList
Closes #242
=> Add support for loading mol2 files in the parmed CLI

parmed/gromacs/gromacstop.py, test/test_format_conversions.py
=> Fix creating GromacsTopologyFile.from_structure with box information

parmed/gromacs/gromacstop.py, test/test_parmed_gromacs.py
=> Fix Gromacs topology file writing when combine='all'

test/test_openmm_amber.py
Should hopefully reduce the frequency of test hangs in Travis.
=> Switch EP and EP2 tests to Reference platform

doc/amber.rst, doc/conf.py, doc/index.rst, doc/readwrite.rst, parmed/structure.py
Other doc improvements.
Closes #332
=> Add docs for load_file and Structure.save

parmed/structure.py, parmed/topologyobjects.py, test/test_parmed_structure.py
=> Fix a couple bugs in Structure stripping with defined coordinates

doc/index.rst, doc/parmed_api.rst
=> Clarify some docs.

parmed/structure.py, test/test_parmed_structure.py
=> Fix handling of setting empty array to Structure.coordinates

doc/readwrite.rst, parmed/amber/asciicrd.py, parmed/structure.py, test/test_parmed_structure.py
=> Adds overwrite argument to Structure.save and rst7/ncrst write support for Structure.save

parmed/modeller/residue.py, test/test_parmed_modeller.py, test/test_parmed_residue.py
Slice Residue with a tuple/list
```python
residue = pmd.load_file(get_fn('aminont12.lib'))['NALA']
residue[['CA', 'CB', 'C', 'N']]
residue[[0, 3, 5, 2]]
```
feel free to update the test to your style. :D
=> Slice residue

parmed/structure.py, parmed/topologyobjects.py, parmed/utils/pandautils.py, test/test_parmed_pandas.py
This commit does a couple things. Major thing it does is add a load_dataframe
instance to Structure so that atomic properties can be set via a DataFrame (it
also works with dicts through duck typing).
This commit *also* adds a to_dataframe method to StructureView and a
load_dataframe method to StructureView
=> Add a load_dataframe method

parmed/modeller/residue.py, test/test_parmed_modeller.py
Also supports `.pdb` extension for `ResidueTemplate.save`.
Closes #379
=> Adds a to_structure in ResidueTemplate

doc/devdoc.rst, doc/index.rst
=> Add developer's documentation

doc/index.rst
=> Fix links.

parmed/amber/_amberparm.py, parmed/amber/_chamberparm.py, parmed/amber/_tinkerparm.py, parmed/residue.py, parmed/structure.py, parmed/tools/actions.py, test/saved_outputs.py, test/test_parmedtools_actions.py
Move name recognition to a centralized location and fix up some references to
it. Also fixes the 'summary' command for PDB files.
Fixes #387
=> Fix up solvent residue handling

parmed/residue.py, parmed/tools/actions.py, test/saved_outputs.py
Also centralizes them in a single place -- residues.py
Fixes #390
=> Improve residue name recognition for summary

parmed/amber/_amberparm.py, parmed/amber/_chamberparm.py, parmed/amber/amberformat.py, test/test_parmed_amber.py
=> Fix behavior of AmberParm.save for an AmberParm

parmed/tools/actions.py, test/saved_outputs.py
the summary's output in this PR is not very pretty for Structure having lots of restypes. But's ok for DNA/RNA. :D
=>  add residue set and residue count for summary

parmed/residue.py, parmed/structure.py, test/test_parmed_structure_slicing.py
It iterates over atoms in the StructureView
=> Make StructureView iteration behave like Structure iteration

test/test_parmed_residue.py
=> add tests for modified residues in 3p4{a,b,d}

parmed/residue.py, parmed/tools/actions.py
=> Adds NA+, CL-, and T to recognized residues

parmed/__init__.py
=> Update version to 2.0

devtools/travis-ci/install.sh, parmed/__init__.py, parmed/charmm/charmmcrds.py, parmed/charmm/psf.py, parmed/formats/pdb.py, parmed/formats/psf.py, parmed/structure.py, parmed/topologyobjects.py, parmed/utils/decorators.py, parmed/utils/pandautils.py, test/test_format_conversions.py, test/test_openmm_amber.py, test/test_openmm_charmm.py, test/test_openmm_gromacs.py, test/test_openmm_reporters.py, test/test_parmed_charmm.py, test/test_parmed_formats.py, test/test_parmed_pandas.py, test/test_parmed_serialization.py, test/utils.py
=> Move segid to Residue

parmed/amber/mdin/mdin.py, test/test_parmed_amber.py
Fixes the MMPBSA.py test error hitting currently.
=> Fix a small bug with setting variables in an Amber mdin file

.travis.yml, devtools/travis-ci/install.sh, parmed/amber/netcdffiles.py, test/test_parmed_netcdf.py
This fixes up ScientificPython support, which has not been reliably tested via
Travis thus far. Also fixes parsing files whose optional attributes are missing
and adds tests for this.
Also tries to add ScientificPython testing to the Travis build matrix.
=> Tidy up NetCDF support and do not error when optional attributes are missing

parmed/__init__.py, parmed/formats/pdb.py, test/test_parmed_formats.py
=> Fix autodetection of PDB files where residue indices start negative

parmed/formats/pdb.py, test/test_parmed_formats.py
=> Fix PDB and CIF file writing when passed external coordinates

parmed/amber/parameters.py, parmed/openmm/__init__.py, parmed/openmm/parameters.py, parmed/parameters.py, parmed/topologyobjects.py, test/test_parmed_openmm.py
This PR adds writing for atom types, residue templates, bond, and angle parameters.
Pinging @jchodera, @chayast, and @rafwiewiora since this should be useful in the Amber/CHARMM conversions.
=> Begin working on XML parameter writing

parmed/openmm/parameters.py, test/files/charmm_conv.xml, test/test_parmed_openmm.py
This fixed this issue 
https://github.com/ParmEd/ParmEd/issues/504
=> fix for cmap

parmed/__init__.py, parmed/structure.py, test/test_parmed_structure.py
=> Fixes bug where you can't add Structures with coordinates

parmed/charmm/parameters.py, parmed/charmm/psf.py, src/readparm.cpp, test/test_parmed_charmm.py
Also deletes some code that is never, and should never be, run. This code was misleading at worst, and useless at best.
=> Add some tests to improve coverage of charmm package

parmed/charmm/psf.py, test/test_parmed_structure.py
=> Fix PSF file writing from Structure with no parameters

MANIFEST.in
https://github.com/pandegroup/openmm/issues/680#issuecomment-170136497
=> Fix sdist generation

parmed/tools/actions.py, test/test_parmedtools_actions.py
=> Fix the `strip` action in the parmed interpreter

parmed/charmm/parameters.py, parmed/openmm/parameters.py, test/test_parmed_openmm.py
I copied @jchodera's ```_write_omm_urey_bradley``` here.
=> Urey Bradley term

parmed/gromacs/gromacstop.py, parmed/topologyobjects.py
Not really important but may as well after #545
=> Write charge to `[ atomtypes ]`

parmed/amber/_amberparm.py, test/test_openmm_amber.py, test/test_parmed_amber.py
Also fixes up a few small potential bugs and error messages (doesn't seem like there were any *real* bugs, though).
=> Add tests for _amberparm.py module

parmed/__init__.py, parmed/structure.py, test/test_openmm_amber.py
Has corresponding test.  See discussion near [my comment in #486](https://github.com/ParmEd/ParmEd/issues/486#issuecomment-172592755)
=> Split up dihedrals into separate proper/improper forces for OpenMM

MANIFEST.in, parmed/__init__.py, parmed/amber/_amberparm.py, parmed/amber/_chamberparm.py, parmed/formats/pdb.py, parmed/gromacs/gromacstop.py, parmed/structure.py, parmed/topologyobjects.py, test/test_format_conversions.py, test/test_openmm_amber.py, test/test_openmm_gromacs.py, test/test_parmed_amber.py, test/test_parmed_formats.py, test/test_parmed_gromacs.py, test/test_parmed_topologyobjects.py, test/test_parmedtools_actions.py, test/utils.py
Merges master branch into ommparams
=> merge master

.travis.yml, doc/devdoc.rst, doc/index.rst, parmed/__init__.py, test/test_parmed_formats.py
=> Deprecate write_PDB and write_CIF

parmed/__init__.py, parmed/amber/_chamberparm.py, test/test_format_conversions.py, test/test_parmed_amber.py
Adds a test case for this as well.  Coverage on this module is up to 99%
=> Fix ChamberParm.from_structure with modified custom exception rules

.travis.yml, devtools/travis-ci/install.sh, devtools/travis-ci/runtest.sh, parmed/__init__.py, parmed/gromacs/_cpp.py, parmed/gromacs/_gromacsfile.py, parmed/gromacs/gromacsgro.py, test/files/saved_scripts/cpptest1, test/files/saved_scripts/cpptest2, test/run_scripts.sh, test/test_parmed_amber.py, test/test_parmed_gromacs.py, test/test_parmed_gromacs_cpp.py
Fixes a number of small issues parsing via `GromacsFile` and adds tests for AmberParm, the `CPreProcessor`, and `GromacsFile` (bringing coverage of the latter two to 100%).
It also adds context manager support to `CPreProcessor`.
This PR also turns on coverage analysis (we'll see how much longer the tests take to run...).  It also adds a script that runs (with coverage) CL scripts (which will be necessary to analyze the coverage and operation of numerous parts of ParmEd).  Right now, it's just applied to the `parmed.gromacs._cpp` module which can act as a raw C-preprocessor via `python -m parmed.gromacs._cpp`
=> Testing and small bug fix enhancements

parmed/amber/parameters.py, parmed/openmm/parameters.py, parmed/parameters.py, test/test_parmed_openmm.py
=> Fix writing XML files for tiny parts of a FF

devtools/travis-ci/runtest.sh, parmed/__init__.py, parmed/amber/offlib.py, parmed/charmm/psf.py, parmed/gromacs/gromacstop.py, parmed/modeller/residue.py, parmed/openmm/reporters.py, parmed/parameters.py, parmed/structure.py, parmed/topologyobjects.py, test/.coveragerc, test/test_openmm_reporters.py, test/test_parmed_gromacs.py, test/test_parmed_modeller.py, test/test_parmed_openmm.py
(nearly complete test coverage...), improve .coveragerc, and fix a few issues.
=> Add more tests for GromacsTopologyFile

parmed/openmm/parameters.py, test/test_parmed_amber.py
Supplement to #582 (going into different branches). 
That's just a whitespace removal on that one line.
=> set empty string element for atomic number 0 (EP/LP)

parmed/charmm/charmmcrds.py, test/test_parmed_formats.py
=> Fix potential hang when identifying type of a short file

parmed/amber/parameters.py, parmed/utils/io.py, test/test_parmed_amber.py, test/test_parmedtools_parmlist.py
Add tests to ParmList and simplify some code in genopen
=> Small tweaks

parmed/topologyobjects.py, test/test_parmed_modeller.py, test/test_parmed_residue.py
=> Fix Atom's `__repr__` when in ResidueTemplate

parmed/charmm/_charmmfile.py, parmed/charmm/parameters.py
This fixes issue https://github.com/ParmEd/ParmEd/issues/600
=> bugfix, inlude END in section

parmed/openmm/parameters.py
Sorry, correcting own mistake from past PR!
=> skip dihedral writing only if no propers AND periodic impropers

parmed/amber/parameters.py, parmed/charmm/parameters.py, test/test_parmed_amber.py, test/test_parmed_charmm.py
=> Support specifying file names with spaces in leaprc files

parmed/__init__.py, parmed/amber/parameters.py, test/.coveragerc, test/test_parmed_amber.py
Closes #592 
@rafwiewiora seems to have his hands full with FF validation, so I went ahead and handled this.  Still need to implement an `AmberParameterSet.join` function in order to support "source", but that's for another PR.
=> Add loadMol2 and loadMol3 support to AmberParameterSet.from_leaprc

parmed/structure.py, test/test_parmed_serialization.py
Fixes #618 
@ChayaSt and @rafwiewiora -- can you check that this fixes the deepcopy issues you were seeing?
=> Fix unknown_functional setting in deserialized Structure instances

parmed/openmm/parameters.py
Needed for leaprc.ff14SB + leaprc.modrna08 in the conversion, modrna08's frcmod does some overriding so this needs to go as a bundle - hence need to be able to pass a list of dictionaries for multiple Source tags.
=> Provenance tweak again - allow list of dictionaries

parmed/structure.py, test/test_parmed_serialization.py
=> Make sure space_group is properly transferred in Structure serialization

devtools/travis-ci/install.sh, parmed/openmm/parameters.py, test/files/atomic_ions.lib, test/test_parmed_openmm.py
=> Expand meaning of write_unused to removing templates using unavailable atom types

.travis.yml, devtools/travis-ci/install.sh
Since there's a conda package for this now, might as well add it to
improve test coverage :)
=> Improve testing coverage by installing pysander

parmed/structure.py, test/test_openmm_amber.py
Hopefully fixes #624 
@ChayaSt -- can you check that this PR fixes what you were seeing?
=> Fix behavior of rigidWater in OpenMM System creation

parmed/__init__.py, parmed/structure.py, test/test_parmed_charmm.py
=> Do not lose segid attribute when copying, slicing, adding, or duplicating Structure

parmed/__init__.py, parmed/gromacs/gromacstop.py
=> Hopefully fix Windows without getting rid of the fix for Unix OSes.

parmed/amber/_amberparm.py, parmed/structure.py, test/test_parmed_amber.py
- add tests for boxes
- fix doc
=>  add tests for boxes

doc/index.rst, doc/parmed_api.rst, doc/readwrite.rst, doc/structure.rst
=> Documentation updates.

doc/rosetta.rst
=> Update PyRosetta docs

parmed/formats/pdb.py
=> Improve docstring for PDB parser a little

parmed/formats/mol2.py, parmed/periodic_table.py, test/test_parmed_formats.py
=> Add atomic number determination to mol2 file parser

parmed/formats/mol2.py, test/test_parmed_formats.py
=> Add a compress_whitespace argument to the mol2 file writer

setup.py
```bash
AmberTools/src (master) $ git ls-files --other |grep parmed
parmed/__pycache__/versioneer.cpython-34.pyc
```
=> clean __pycache__ in root folder

parmed/formats/psf.py, test/files/saved/amber_to_charmm.psf, test/test_parmed_charmm.py
=> Write the XPLOR flag to CHARMM PSF files if it is warranted

parmed/formats/pdb.py
=> Add some clarifying documentation to pdb.py

devtools/travis-ci/install.sh, parmed/rdkit/rdkit.py, test/test_parmed_rdkit.py
=> add coordinates for `parmed.rdkit.from_smiles`

parmed/charmm/parameters.py, parmed/charmm/psf.py, test/test_parmed_charmm.py
+ seems to be an illegal character.
=> Make sure that + does not appear in any charmm atom type names

README.md
close
https://github.com/ParmEd/ParmEd/issues/717
=> Readme - update setup info + minimal example

parmed/modeller/residue.py, parmed/openmm/parameters.py, test/test_parmed_openmm.py
New PR here, should be without conflicts now.
=> Change overload to override

parmed/amber/_amberparm.py, parmed/amber/_chamberparm.py, parmed/structure.py, test/test_parmed_structure_slicing.py
=> copying box, symmetry, space_group when slicing Structure

parmed/formats/__init__.py, parmed/formats/registry.py, parmed/formats/sdf.py, parmed/rdkit/__init__.py, parmed/rdkit/rdkit.py, test/files/test.sdf, test/test_parmed_formats.py, test/test_parmed_rdkit.py
still  better than nothing. added very minimal test.
related to https://github.com/ParmEd/ParmEd/issues/334
=> parse sdf format via rdkit

README.md
update example from your comment: https://github.com/ParmEd/ParmEd/issues/631#issuecomment-193555313
=> amber to others: example

devtools/travis-ci/install.sh, parmed/tools/actions.py, parmed/tools/simulations/sanderapi.py, test/test_parmedtools_actions.py
Still got problem with 
`Problem minimizing structure with scipy and sander:
b'\tSTOP: TOTAL NO. of ITERATIONS EXCEEDS LIMIT'
`
=> fix bytes + add some tests for minimization + increase code coverage

parmed/amber/netcdffiles.py, parmed/amber/parameters.py, test/test_parmed_amber.py
=> Increase precision of generated frcmod files

parmed/amber/_amberparm.py
This should have been included in #803
=> Copy the coordinates to avoid unintended side-effects

parmed/amber/asciicrd.py, test/test_parmed_formats.py
also fix #https://github.com/ParmEd/ParmEd/issues/778 (if convert to Structure)
=> add structure=True for rst7

parmed/tools/simulations/sanderapi.py
=> add callback function to minimize (so we can visualize the minimization process with nglview)

parmed/tools/simulations/sanderapi.py
Can you turn on the minimization test?
or make different test file for this.
It's clearly that this bug is not captured in previous PR #825
=> oops, fix syntax error for minimize

parmed/formats/pdb.py, test/test_parmed_formats.py
=> Fix bug in PDB parser with test

parmed/formats/pdb.py
Fixes issues in PDB parsing for pdb4amber and Phenix
=> Stop reading column 21 as a 4th letter of the residue

parmed/amber/mdin/pb.py
This is from commit edd12f2573941e393ead6743891306c267eecc40 in the Amber repository.
=> Incorporate changes from AmberTools into ParmEd

parmed/amber/_amberparm.py, parmed/amber/_tinkerparm.py, parmed/constants.py, parmed/structure.py, test/files/nma.parm7, test/saved_outputs.py, test/test_format_conversions.py, test/test_parmed_amber.py, test/test_parmed_openmm.py, test/utils.py
Finally fixes #724 (and replaces #726)
=> Set IFBOX to 3 in Amber prmtop file if box is not orthogonal or octahedral

parmed/tools/actions.py
=> Fix horrific performance regression in tiMerge

parmed/charmm/parameters.py
=> Fix converting molecules to CHARMM that *have* no torsion terms

devtools/ci/jenkins/install.sh, parmed/geometry.py, parmed/topologyobjects.py, test/test_parmed_topologyobjects.py
=> Add unit(ed) properties to topology objects

parmed/charmm/parameters.py, parmed/charmm/psf.py, parmed/modeller/residue.py, parmed/openmm/parameters.py, test/files/charmm.xml, test/test_parmed_charmm.py, test/test_parmed_openmm.py
This PR includes the changes to write out impropers explicitly for OpnenMM `ffxml` files.
=> Write out explicit impropers

parmed/amber/_amberparm.py, test/test_parmed_amber.py, test/test_parmed_serialization.py
Fix for #874, along with a couple of additional and modified tests for this issue.
=> Fix pickling issues with AmberParm objects

devtools/ci/jenkins/install.sh
Not a pretty solution, but hopefully marginally robust :(
=> Try to work around a race condition on Jenkins

parmed/openmm/topsystem.py, parmed/topologyobjects.py
=> Improve converting OpenMM to GROMACS

parmed/formats/psf.py, test/files/saved/amber_to_charmm.psf, test/test_openmm_reporters.py
=> Make sure a newline is at the end of PSF files.

parmed/charmm/psf.py
=> Match parameters on uppercase types for CHARMM PSF

parmed/structure.py
This is a fix for the issues: [https://github.com/ParmEd/ParmEd/issues/958](https://github.com/ParmEd/ParmEd/issues/958) and [https://github.com/ParmEd/ParmEd/issues/959](https://github.com/ParmEd/ParmEd/issues/959)
=> [WIP] Fix OpenMM Constraints

parmed/amber/_amberparm.py, parmed/structure.py
Fixes #756 
Fixes #840 
Fixes #952
=> Try to fix #756, #840, and #952

devtools/ci/travis/install.sh, devtools/ci/travis/runtest.sh, parmed/amber/offlib.py, parmed/utils/netcdf.py, src/main.cpp
=> Fix a regex to accommodate trailing spaces.

parmed/openmm/parameters.py, test/test_parmed_openmm.py
Fixes #999 
This is a WIP. I'm trying to figure out why surprisingly few patches are being judged as equivalent now.
=> Update logic for comparing OpenMM XML patches for equivalence

parmed/gromacs/gromacstop.py, parmed/parameters.py, test/test_parmed_parameterset.py
It [looks](https://github.com/ParmEd/ParmEd/blame/master/parmed/parameters.py) like this is something that slipped through the cracks
=> Populate parameterset.nbfix_types in from_structure

setup.py
=> Hacky workaround for conda Python on macs.

parmed/charmm/parameters.py, parmed/formats/pdb.py
=> Do not make lonepair support fatal when it is not a supported type

parmed/formats/pdb.py, parmed/structure.py
This is the volume, not the volume page
=> volume_page is not ever assigned to, it's volume

doc/visualization.rst
hi, I am adding one more example here. Cheers. (Online view is here: https://github.com/arose/nglview/blob/master/examples/parmed_minimization.md)
=> visualization of structure minimization

parmed/tools/actions.py, setup.py
=> Make the default chain ID Z instead of *

devtools/ci/travis/install.sh, parmed/charmm/charmmcrds.py
=> Do not try to parse field as int that file spec says should just be string

parmed/tools/changeradii.py
The bondi radii already matched.  Everything else is adjusted to match as well.
=> Fix Cl radii to match tleap

parmed/charmm/psf.py, parmed/structure.py, test/test_parmed_charmm.py
Fixes some obscure PSF parsing issues as well as conversion of this file to GROMACS.
=> Fixes #976

parmed/amber/_amberparm.py, parmed/amber/parameters.py
=> Fix some imports and fix possible (but rare) div-by-zero error.

.travis.yml, devtools/ci/travis/install.sh, parmed/charmm/parameters.py, parmed/modeller/residue.py, parmed/openmm/parameters.py, parmed/topologyobjects.py
Initial implementation of #1080.  I've added support for loading Drude particles from CHARMM files and writing them to OpenMM force fields.  I'm still working on testing and making some required changes to OpenMM, but this is basically complete and functional.
=> Add support for Drude particles

parmed/gromacs/gromacstop.py, test/test_parmed_gromacs.py
Fixes #1094 
Pushing as separate commits to ensure the patch actually fixes the bug as it does locally (test-driven development and all)
=> Fix nonbond_params parsing and test

setup.py
=> Try to fix osx builds more permanently

parmed/structure.py, test/test_openmm_amber.py
I copied the implementations of the forces from ForceField and verified that the test cases pass.
=> Converted AMOEBA code to work with OpenMM 7.6

parmed/tools/simulations/sanderapi.py
We switched away from %-formatting to str.format
=> Fix energy printout

.gitignore, README.md, ccd.js, get_hybridization_from_rdkit.py, parmed/formats/pdb.py, parmed/modeller/__init__.py, parmed/modeller/residue.py, parmed/modeller/standardtemplates.py, parmed/rdkit/rdkit.py, parmed/structure.py, parmed/topologyobjects.py, setup.py, test/files/1az5.cif, test/files/1az5.pdb, test/files/2src.cif, test/files/2src.pdb, test/files/test_nonbond_params.top, test/test_parmed_formats.py, test/test_parmed_genopen.py, test/test_parmed_structure.py, test/utils.py
This adds all RNA, DNA, and protein/peptide residues as defined in the PDB chemical component database that are "linking" residues.
=> Improve CIF and PDB parsing and add informatics fields to Atom and Bond

parmed/geometry.py, test/test_parmed_geometry.py
I hope there is agreement as to how something like this could be useful. I included a test to show how you can place atoms based on internal coordinates using a Z-matrix-like entry.
=> Basic routines for internal to cartesian coordinate conversion

parmed/structure.py
This PR sets the chain IDs in `Structure.topology` to match those in the `Structure` object.
=> Transfer chain IDs to OpenMM topology.

parmed/modeller/standardtemplates.py
=> Fix Python 3.8 support

parmed/amber/parameters.py
=> Fix wildcard sorting when writing Amber parameter sets (fixes #1347)

parmed/topologyobjects.py
=> Bugfixed AtomType equality operator

parmed/amber/_amberparm.py, parmed/amber/asciicrd.py, parmed/amber/netcdffiles.py, parmed/formats/pdb.py, parmed/formats/pqr.py, parmed/structure.py
=> Fixed compatibility with NumPy 2.0+

parmed/structure.py, test/test_parmed_serialization.py
=> Fix serialization of structure with bond type attributes and add test

parmed/tools/simulations/openmm.py
Occasionally was getting an error from OpenMM that box vectors were not in the [reduced form that it expects](https://github.com/openmm/openmm/blob/8defca2d65a672bcac199a1cab83807b9522bc19/openmmapi/src/System.cpp#L129-L130) after exporting a trajectory frame into an Amber restart file and starting from that with ParmEd (perhaps natively produced restart files are already in reduced form). Interestingly, ParmEd already has the function `reduce_box_vectors` that is used [when loading from GROMACS gro files](https://github.com/ParmEd/ParmEd/blob/cd0f8789134e123d7127bc04560412ab740ccfe2/parmed/gromacs/gromacsgro.py#L298), so I just applied that in the openmm simulations module to enforce it.
=> Ensure PBC box vectors are in reduced form for OpenMM

parmed/amber/mdin/mdin.py
The existing implementation of Amber mdin parsing splits fields at ',' and '=', but this causes issues with the restraintmask field that can use '=' for wildcards, e.g. `'!@H='` would be used to do "don't restrain any H atom" (i.e. restrain only heavy atoms). So I've changed the splitting with regex and other checks for quoted field values.
=> Improve mdin parsing to not split restraintmask fields using '=' wildcard char

parmed/tools/simulations/openmm.py
Closes #1366 - I thought I'd go ahead and submit a PR for it since there are a couple more fixes/mods I am going to submit anyway.
=> Fix velocity unit scale for existing vels passed to OpenMM
